// Baked monocular depth maps (Depth Anything V2, generated by
// scripts/generate-depth-maps.mjs). Bright = near, dark = far. Imported as Vite
// assets so they're hashed and served with the correct base path.
import centralMarketPast from './depth/central-market.past.png';
import centralMarketNow from './depth/central-market.now.png';
import courtPast from './depth/court-of-final-appeal.past.png';
import courtNow from './depth/court-of-final-appeal.now.png';
import leeTungPast from './depth/lee-tung-street.past.png';
import leeTungNow from './depth/lee-tung-street.now.png';
import blueHousePast from './depth/blue-house.past.png';
import blueHouseNow from './depth/blue-house.now.png';
import happyValleyPast from './depth/happy-valley-racecourse.past.png';
import happyValleyNow from './depth/happy-valley-racecourse.now.png';

export const depthMaps = {
  'central-market': { past: centralMarketPast, now: centralMarketNow },
  'court-of-final-appeal': { past: courtPast, now: courtNow },
  'lee-tung-street': { past: leeTungPast, now: leeTungNow },
  'blue-house': { past: blueHousePast, now: blueHouseNow },
  'happy-valley-racecourse': { past: happyValleyPast, now: happyValleyNow },
};
