// Verified place images (Student C). All from Wikimedia Commons, checked by hand.
// `image` = main image per place (A's schema). `gallery` = then-and-now set, oldest first.
// Show `credit` under any image whose `attributionRequired` is true (CC BY / CC BY-SA).
// Checked: 2026-09-26. Every url was loaded successfully on that date.

export const placeImages = {
  'central-market': {
    image: {
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/HK_CH_%E4%B8%AD%E7%92%B0_Central_%E5%BE%B7%E8%BC%94%E9%81%93%E4%B8%AD_Des_Voeux_Road_Central_Market_building_March_2026_N13P_01.jpg/1280px-HK_CH_%E4%B8%AD%E7%92%B0_Central_%E5%BE%B7%E8%BC%94%E9%81%93%E4%B8%AD_Des_Voeux_Road_Central_Market_building_March_2026_N13P_01.jpg",
      alt: "Central Market on Des Voeux Road Central after revitalisation, March 2026",
      altZh: "2026年3月，活化后的中环街市（德辅道中）",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:HK_CH_%E4%B8%AD%E7%92%B0_Central_%E5%BE%B7%E8%BC%94%E9%81%93%E4%B8%AD_Des_Voeux_Road_Central_Market_building_March_2026_N13P_01.jpg",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      author: "Luksongm MWLLOPPEE",
      credit: "Photo: Luksongm MWLLOPPEE / CC0, via Wikimedia Commons",
      attributionRequired: false,
      date: "2026-03-06",
      era: "now",
      originalUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b6/HK_CH_%E4%B8%AD%E7%92%B0_Central_%E5%BE%B7%E8%BC%94%E9%81%93%E4%B8%AD_Des_Voeux_Road_Central_Market_building_March_2026_N13P_01.jpg",
      status: "verified",
    },
    gallery: [
      { id: "A4",
        url: "https://upload.wikimedia.org/wikipedia/commons/6/69/%E9%A6%99%E6%B8%AF_Hong_Kong_%E4%B8%AD%E7%92%B0%E8%A1%97%E5%B8%82_Central_Market%2C_1930s.jpg",
        alt: "Central Market shortly after completion, 1930s",
        altZh: "1930年代刚落成的中环街市",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:%E9%A6%99%E6%B8%AF_Hong_Kong_%E4%B8%AD%E7%92%B0%E8%A1%97%E5%B8%82_Central_Market%2C_1930s.jpg",
        license: "Public domain",
        licenseUrl: "",
        author: "Unknown author",
        credit: "Public domain, via Wikimedia Commons",
        attributionRequired: false,
        date: "1930s",
        era: "past",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/6/69/%E9%A6%99%E6%B8%AF_Hong_Kong_%E4%B8%AD%E7%92%B0%E8%A1%97%E5%B8%82_Central_Market%2C_1930s.jpg",
        status: "verified",
      },
      { id: "A2",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/HK_CH_%E4%B8%AD%E7%92%B0_Central_%E5%BE%B7%E8%BC%94%E9%81%93%E4%B8%AD_Des_Voeux_Road_Central_Market_building_March_2026_N13P_01.jpg/1280px-HK_CH_%E4%B8%AD%E7%92%B0_Central_%E5%BE%B7%E8%BC%94%E9%81%93%E4%B8%AD_Des_Voeux_Road_Central_Market_building_March_2026_N13P_01.jpg",
        alt: "Central Market on Des Voeux Road Central after revitalisation, March 2026",
        altZh: "2026年3月，活化后的中环街市（德辅道中）",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:HK_CH_%E4%B8%AD%E7%92%B0_Central_%E5%BE%B7%E8%BC%94%E9%81%93%E4%B8%AD_Des_Voeux_Road_Central_Market_building_March_2026_N13P_01.jpg",
        license: "CC0",
        licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
        author: "Luksongm MWLLOPPEE",
        credit: "Photo: Luksongm MWLLOPPEE / CC0, via Wikimedia Commons",
        attributionRequired: false,
        date: "2026-03-06",
        era: "now",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b6/HK_CH_%E4%B8%AD%E7%92%B0_Central_%E5%BE%B7%E8%BC%94%E9%81%93%E4%B8%AD_Des_Voeux_Road_Central_Market_building_March_2026_N13P_01.jpg",
        status: "verified",
      },
    ],
  },
  'court-of-final-appeal': {
    image: {
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Court_of_Final_Appeal_Building.jpg/1280px-Court_of_Final_Appeal_Building.jpg",
      alt: "Aerial view of the Court of Final Appeal Building beside Statue Square, 2022",
      altZh: "2022年俯瞰皇后像广场旁的终审法院大楼",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Court_of_Final_Appeal_Building.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
      author: "THE LION ROCK",
      credit: "Photo: THE LION ROCK / CC BY-SA 4.0, via Wikimedia Commons",
      attributionRequired: true,
      date: "2022-03-15",
      era: "now",
      originalUrl: "https://upload.wikimedia.org/wikipedia/commons/9/93/Court_of_Final_Appeal_Building.jpg",
      status: "verified",
    },
    gallery: [
      { id: "B5",
        url: "https://upload.wikimedia.org/wikipedia/commons/c/cb/HK_Statue_Square_circa_1930s.jpg",
        alt: "Statue Square with the Supreme Court building, late 1920s to 1930s",
        altZh: "约1920年代末至1930年代的皇后像广场与最高法院大楼",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:HK_Statue_Square_circa_1930s.jpg",
        license: "Public domain",
        licenseUrl: "",
        author: "Unknown author (uploaded by Kevinhksouth, Chinese Wikipedia)",
        credit: "Public domain, via Wikimedia Commons",
        attributionRequired: false,
        date: "c. late 1920s–1930s",
        era: "past",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cb/HK_Statue_Square_circa_1930s.jpg",
        status: "verified",
      },
      { id: "B6",
        url: "https://upload.wikimedia.org/wikipedia/commons/4/42/HK_Central_Statue_Square_Legislative_Council_Building_n_Themis_n_Lions_n_Dieu_et_mon_droit.JPG",
        alt: "The building's facade during its Legislative Council years, 2008",
        altZh: "2008年立法会时期的大楼正面与女神像",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:HK_Central_Statue_Square_Legislative_Council_Building_n_Themis_n_Lions_n_Dieu_et_mon_droit.JPG",
        license: "CC BY-SA 3.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
        author: "ChvhLR10",
        credit: "Photo: ChvhLR10 / CC BY-SA 3.0, via Wikimedia Commons",
        attributionRequired: true,
        date: "2008-09-02",
        era: "past",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/4/42/HK_Central_Statue_Square_Legislative_Council_Building_n_Themis_n_Lions_n_Dieu_et_mon_droit.JPG",
        status: "verified",
      },
      { id: "B8",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/The_Exterior_of_the_Old_Supreme_Court.JPG/1280px-The_Exterior_of_the_Old_Supreme_Court.JPG",
        alt: "Facade of the Old Supreme Court Building, 2013",
        altZh: "2013年的旧最高法院大楼外观",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:The_Exterior_of_the_Old_Supreme_Court.JPG",
        license: "CC BY-SA 3.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
        author: "Regina800809",
        credit: "Photo: Regina800809 / CC BY-SA 3.0, via Wikimedia Commons",
        attributionRequired: true,
        date: "2013-07-10",
        era: "past",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/4/47/The_Exterior_of_the_Old_Supreme_Court.JPG",
        status: "verified",
      },
      { id: "B3",
        url: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Hong_Kong_and_the_Scales_of_Justice.jpg",
        alt: "Blindfolded statue of Themis on the Court of Final Appeal Building",
        altZh: "终审法院大楼上蒙眼的正义女神忒弥斯像",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Hong_Kong_and_the_Scales_of_Justice.jpg",
        license: "CC0",
        licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
        author: "Scotted400",
        credit: "Photo: Scotted400 / CC0, via Wikimedia Commons",
        attributionRequired: false,
        date: "2020-08-18",
        era: "detail",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Hong_Kong_and_the_Scales_of_Justice.jpg",
        status: "verified",
      },
      { id: "B1",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Court_of_Final_Appeal_Building.jpg/1280px-Court_of_Final_Appeal_Building.jpg",
        alt: "Aerial view of the Court of Final Appeal Building beside Statue Square, 2022",
        altZh: "2022年俯瞰皇后像广场旁的终审法院大楼",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Court_of_Final_Appeal_Building.jpg",
        license: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        author: "THE LION ROCK",
        credit: "Photo: THE LION ROCK / CC BY-SA 4.0, via Wikimedia Commons",
        attributionRequired: true,
        date: "2022-03-15",
        era: "now",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/9/93/Court_of_Final_Appeal_Building.jpg",
        status: "verified",
      },
    ],
  },
  'lee-tung-street': {
    image: {
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Lee_Tung_Avenue_21-01-2023.jpg/1280px-Lee_Tung_Avenue_21-01-2023.jpg",
      alt: "Lee Tung Avenue with red lanterns, 2023",
      altZh: "2023年挂着红灯笼的利东街",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Lee_Tung_Avenue_21-01-2023.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
      author: "LN9267",
      credit: "Photo: LN9267 / CC BY-SA 4.0, via Wikimedia Commons",
      attributionRequired: true,
      date: "2023-01-21",
      era: "now",
      originalUrl: "https://upload.wikimedia.org/wikipedia/commons/7/74/Lee_Tung_Avenue_21-01-2023.jpg",
      status: "verified",
    },
    gallery: [
      { id: "C2",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Lee_Tung_Street.JPG/1280px-Lee_Tung_Street.JPG",
        alt: "Lee Tung Street tenements hung with residents' protest banners, 2005",
        altZh: "2005年利东街唐楼挂满居民的抗议横幅",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Lee_Tung_Street.JPG",
        license: "CC BY-SA 3.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
        author: "Mcy jerry (English Wikipedia)",
        credit: "Photo: Mcy jerry (English Wikipedia) / CC BY-SA 3.0, via Wikimedia Commons",
        attributionRequired: true,
        date: "2005-06-05",
        era: "past",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/5/52/Lee_Tung_Street.JPG",
        status: "verified",
      },
      { id: "C3",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Leetungst.jpg/1280px-Leetungst.jpg",
        alt: "Printing shop signs along Lee Tung Street before demolition, 2006",
        altZh: "2006年清拆前利东街的印刷店招牌",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Leetungst.jpg",
        license: "Public domain",
        licenseUrl: "",
        author: "Rysher (Chinese Wikipedia)",
        credit: "Public domain, via Wikimedia Commons",
        attributionRequired: false,
        date: "2006-08-10",
        era: "past",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Leetungst.jpg",
        status: "verified",
      },
      { id: "C5",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/HK_LeeTungStreet.JPG/1280px-HK_LeeTungStreet.JPG",
        alt: "Lee Tung Street sign during clearance, 2007",
        altZh: "2007年清拆期间的利东街路牌",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:HK_LeeTungStreet.JPG",
        license: "Public domain",
        licenseUrl: "",
        author: "Chong Fat",
        credit: "Public domain, via Wikimedia Commons",
        attributionRequired: false,
        date: "2007-11-13",
        era: "past",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c0/HK_LeeTungStreet.JPG",
        status: "verified",
      },
      { id: "C6",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/HK_Sunday_Wan_Chai_Lee_Tung_Street_n_Hopewell_Centre_Queen_s_Road_East_a.jpg/1280px-HK_Sunday_Wan_Chai_Lee_Tung_Street_n_Hopewell_Centre_Queen_s_Road_East_a.jpg",
        alt: "Lee Tung Street entrance at Queen's Road East, 2008",
        altZh: "2008年皇后大道东的利东街街口",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:HK_Sunday_Wan_Chai_Lee_Tung_Street_n_Hopewell_Centre_Queen_s_Road_East_a.jpg",
        license: "CC BY-SA 3.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
        author: "LeetungTong",
        credit: "Photo: LeetungTong / CC BY-SA 3.0, via Wikimedia Commons",
        attributionRequired: true,
        date: "2008-09-26",
        era: "past",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/c/ce/HK_Sunday_Wan_Chai_Lee_Tung_Street_n_Hopewell_Centre_Queen_s_Road_East_a.jpg",
        status: "verified",
      },
      { id: "C8",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Lee_Tung_Avenue_23-05-2016%281%29.jpg/1280px-Lee_Tung_Avenue_23-05-2016%281%29.jpg",
        alt: "Lee Tung Avenue entrance arch at Queen's Road East, 2016",
        altZh: "2016年皇后大道东的利东街入口拱门",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Lee_Tung_Avenue_23-05-2016%281%29.jpg",
        license: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        author: "LN9267",
        credit: "Photo: LN9267 / CC BY-SA 4.0, via Wikimedia Commons",
        attributionRequired: true,
        date: "2016-05-23",
        era: "now",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/4/45/Lee_Tung_Avenue_23-05-2016%281%29.jpg",
        status: "verified",
      },
      { id: "C7",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Lee_Tung_Avenue_21-01-2023.jpg/1280px-Lee_Tung_Avenue_21-01-2023.jpg",
        alt: "Lee Tung Avenue with red lanterns, 2023",
        altZh: "2023年挂着红灯笼的利东街",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Lee_Tung_Avenue_21-01-2023.jpg",
        license: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        author: "LN9267",
        credit: "Photo: LN9267 / CC BY-SA 4.0, via Wikimedia Commons",
        attributionRequired: true,
        date: "2023-01-21",
        era: "now",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/7/74/Lee_Tung_Avenue_21-01-2023.jpg",
        status: "verified",
      },
      { id: "C11",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Lee_Tung_Avenue_17-12-2023.jpg/1280px-Lee_Tung_Avenue_17-12-2023.jpg",
        alt: "Lee Tung Avenue street view, December 2023",
        altZh: "2023年12月的利东街街景",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Lee_Tung_Avenue_17-12-2023.jpg",
        license: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        author: "LN9267",
        credit: "Photo: LN9267 / CC BY-SA 4.0, via Wikimedia Commons",
        attributionRequired: true,
        date: "2023-12-17",
        era: "now",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Lee_Tung_Avenue_17-12-2023.jpg",
        status: "verified",
      },
    ],
  },
  'blue-house': {
    image: {
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Blue_House_in_February_2025.jpg/1280px-Blue_House_in_February_2025.jpg",
      alt: "Restored Blue House on Stone Nullah Lane, 2025",
      altZh: "2025年修复后的石水渠街蓝屋",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Blue_House_in_February_2025.jpg",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      author: "姒姓賢寧",
      credit: "Photo: 姒姓賢寧 / CC BY 4.0, via Wikimedia Commons",
      attributionRequired: true,
      date: "2025-02-22",
      era: "now",
      originalUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Blue_House_in_February_2025.jpg",
      status: "verified",
    },
    gallery: [
      { id: "D5",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Blue_House_HK.jpg/1280px-Blue_House_HK.jpg",
        alt: "Blue House before revitalisation, with laundry on the balconies, 2006",
        altZh: "2006年活化前的蓝屋，阳台晾着衣服",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Blue_House_HK.jpg",
        license: "CC BY-SA 3.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
        author: "Pedist",
        credit: "Photo: Pedist / CC BY-SA 3.0, via Wikimedia Commons",
        attributionRequired: true,
        date: "2006-08-31",
        era: "past",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6c/Blue_House_HK.jpg",
        status: "verified",
      },
      { id: "D1",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Wan_Chai_Blue_House.JPG/1280px-Wan_Chai_Blue_House.JPG",
        alt: "Blue House on Stone Nullah Lane during restoration works, 2013",
        altZh: "2013年修复工程中的石水渠街蓝屋",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Wan_Chai_Blue_House.JPG",
        license: "CC BY-SA 3.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
        author: "Gloriashek91",
        credit: "Photo: Gloriashek91 / CC BY-SA 3.0, via Wikimedia Commons",
        attributionRequired: true,
        date: "2013-08-03",
        era: "past",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Wan_Chai_Blue_House.JPG",
        status: "verified",
      },
      { id: "D9",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Hong_Kong_%282017%29_-_532.jpg/1280px-Hong_Kong_%282017%29_-_532.jpg",
        alt: "Blue House beside the Yellow House, 2017",
        altZh: "2017年蓝屋与旁边的黄屋",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Hong_Kong_%282017%29_-_532.jpg",
        license: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        author: "Another Believer",
        credit: "Photo: Another Believer / CC BY-SA 4.0, via Wikimedia Commons",
        attributionRequired: true,
        date: "2017-11-22",
        era: "now",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Hong_Kong_%282017%29_-_532.jpg",
        status: "verified",
      },
      { id: "D6",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Blue_House_in_February_2025.jpg/1280px-Blue_House_in_February_2025.jpg",
        alt: "Restored Blue House on Stone Nullah Lane, 2025",
        altZh: "2025年修复后的石水渠街蓝屋",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Blue_House_in_February_2025.jpg",
        license: "CC BY 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
        author: "姒姓賢寧",
        credit: "Photo: 姒姓賢寧 / CC BY 4.0, via Wikimedia Commons",
        attributionRequired: true,
        date: "2025-02-22",
        era: "now",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Blue_House_in_February_2025.jpg",
        status: "verified",
      },
    ],
  },
  'happy-valley-racecourse': {
    image: {
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Race_Course_Fire_Memorial_20160221_173208.jpg/1280px-Race_Course_Fire_Memorial_20160221_173208.jpg",
      alt: "Race Course Fire Memorial at So Kon Po",
      altZh: "掃桿埔的马场火灾纪念碑",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Race_Course_Fire_Memorial_20160221_173208.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
      author: "John Cruel",
      credit: "Photo: John Cruel / CC BY-SA 4.0, via Wikimedia Commons",
      attributionRequired: true,
      date: "2016-02-21",
      era: "now",
      originalUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ac/Race_Course_Fire_Memorial_20160221_173208.jpg",
      status: "verified",
    },
    gallery: [
      { id: "E6",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/HappyvalleyfireHK1918.jpg/1280px-HappyvalleyfireHK1918.jpg",
        alt: "Smoke over Happy Valley Racecourse during the fire, 26 February 1918",
        altZh: "1918年2月26日跑马地马场火灾现场",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:HappyvalleyfireHK1918.jpg",
        license: "Public domain",
        licenseUrl: "",
        author: "Unknown author",
        credit: "Public domain, via Wikimedia Commons",
        attributionRequired: false,
        date: "1918-02-26",
        era: "past",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/9/99/HappyvalleyfireHK1918.jpg",
        contentWarning: "Shows the 1918 fire; do not use as a cover image.",
        status: "verified",
      },
      { id: "E7",
        url: "https://upload.wikimedia.org/wikipedia/commons/7/71/Happy_Valley_Racecourse_before_fire_on_26th_February_1918.jpg",
        alt: "Crowds at Happy Valley Racecourse before the fire, 26 February 1918",
        altZh: "1918年2月26日火灾发生前的跑马地马场",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Happy_Valley_Racecourse_before_fire_on_26th_February_1918.jpg",
        license: "Public domain",
        licenseUrl: "",
        author: "Unknown author",
        credit: "Public domain, via Wikimedia Commons",
        attributionRequired: false,
        date: "1918-02-26",
        era: "past",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/7/71/Happy_Valley_Racecourse_before_fire_on_26th_February_1918.jpg",
        status: "verified",
      },
      { id: "E3",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Race_Course_Fire_Memorial_20160221_173208.jpg/1280px-Race_Course_Fire_Memorial_20160221_173208.jpg",
        alt: "Race Course Fire Memorial at So Kon Po",
        altZh: "掃桿埔的马场火灾纪念碑",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Race_Course_Fire_Memorial_20160221_173208.jpg",
        license: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        author: "John Cruel",
        credit: "Photo: John Cruel / CC BY-SA 4.0, via Wikimedia Commons",
        attributionRequired: true,
        date: "2016-02-21",
        era: "now",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ac/Race_Course_Fire_Memorial_20160221_173208.jpg",
        status: "verified",
      },
      { id: "E9",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Race_Course_Fire_Memorial_20160221_173752.jpg/1280px-Race_Course_Fire_Memorial_20160221_173752.jpg",
        alt: "Pagoda on the lowest terrace of the Race Course Fire Memorial",
        altZh: "马场火灾纪念碑最低一层的宝塔",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Race_Course_Fire_Memorial_20160221_173752.jpg",
        license: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        author: "John Cruel",
        credit: "Photo: John Cruel / CC BY-SA 4.0, via Wikimedia Commons",
        attributionRequired: true,
        date: "2016-02-21",
        era: "detail",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Race_Course_Fire_Memorial_20160221_173752.jpg",
        status: "verified",
      },
      { id: "E5",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Hong_Kong_Race_Course_Memorial.jpg/1280px-Hong_Kong_Race_Course_Memorial.jpg",
        alt: "Overview of the Race Course Fire Memorial, 2018",
        altZh: "2018年马场火灾纪念碑全景",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Hong_Kong_Race_Course_Memorial.jpg",
        license: "CC0",
        licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
        author: "Anthony Ivanoff",
        credit: "Photo: Anthony Ivanoff / CC0, via Wikimedia Commons",
        attributionRequired: false,
        date: "2018-02-24",
        era: "now",
        originalUrl: "https://upload.wikimedia.org/wikipedia/commons/7/76/Hong_Kong_Race_Course_Memorial.jpg",
        status: "verified",
      },
    ],
  },
};
